feature/webstore-050
sokimaaa/webstore pull request #29
Opened 2023-05-16 20:11 UTC by alexMIRON1

2023-05-16 20:15 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/controller/FurnitureUnitController.java
>  @RequestMapping("/api/v1/furnitureUnits")
violate resource name convention

2023-05-16 20:16 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/controller/FurnitureUnitController.java
> +        int maxRecords = 3;
max records? hard coded?

2023-05-16 20:36 UTC, sokimaaa requested changes

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/controller/FurnitureUnitController.java
>      }
remove previous endpoints was unnecessary

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/domain/dto/FurnitureUnitResponse.java
> +    private Long id;
I suppose, dont need to return Id

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/domain/dto/FurnitureUnitResponse.java
> +    private int popularityOfFurniture;
you are ignoring this field, but this dto uses for response?

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +@Component
@Component should have been unnecessary

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitService.java
> +            log.error("Was provided wrong furniture unit id -> {}", id);
Is it critical error? or just an exceptional situation 
(if users can provide wrong furniture id, log message should be info)

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitService.java
> +            throw new IllegalArgumentException("Was not found furniture unit by this id " + id);
bad choice to throw Illegal...Exception()
more suitable would be NotFoundException or the same

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureView.java
> +    @OneToOne
View should not have had a relations

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureView.java
> +    @OneToOne
and actually it does not make sense

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_furniture_view.sql
> +(
View is not the same as Table. 
Check the `Repeatable Migrations` in Flyway, make it there.

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_furniture_view.sql
> +(
research what is `View` in postgres (and at all) and for what you need to create it

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_furniture_view.sql
> +(
script will change accordingly, e.g. create View name as select ....

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_furniture_view.sql
> +(
if it's not a View rename it

2023-05-16 20:36 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/local/V229__insert_data_furniture_view.sql
> +       (furniture_view_id, furniture_unit_id, count_view) values
haven't we discussed about a few column for view? 
e.g. viewPerDay, totalView

2023-05-16 20:39 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureView.java
> +    @OneToOne
If it's `table` all well, I would suggest to put away field `id`

2023-05-17 12:50 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureView.java
> +    @OneToOne
okay, so why you name it `View`

2023-05-17 13:06 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureView.java
> +    @OneToOne
Because it was appropriate word, but okay, i got it,  i've alredy rename it

2023-05-19 21:43 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +    private final FurnitureOverviewRepository furnitureOverviewRepository;
Schedule Job as well as Controllers wants to use Service and should not consist any logic. 

It's responsible for scheduling only.

2023-05-19 21:43 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +        furnitureOverviewRepository.resetFurnitureViewCountView();
lack of log messages

2023-05-19 21:44 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +    private final FurnitureOverviewRepository furnitureOverviewRepository;
Will repository be injected? Do you test it?

2023-05-19 21:46 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/TopFurnitureUnitJob.java
> +    private final FurnitureUnitService furnitureUnitService;
Will service be injected?

2023-05-19 21:48 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitCacheService.java
> +        ObjectMapper objectMapper = new ObjectMapper();
creating objects via `new` in spring bad practice.
create in common module configuration to configure and create bean of object mapper's.
There are possible a bunch of ObjectMapper (JSON, XML, plain text and so on), so use qualifiers.

2023-05-19 21:50 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitCacheService.java
> +            valueWrapper = cache.get("topFurnitureUnits");
topFurnitureUnits may be constant, right?

2023-05-19 21:52 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitService.java
> +@EnableCaching
Should @EnableCaching be on config class?

2023-05-19 22:01 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/model/FurnitureOverview.java
> +    public static final String FURNITURE_VIEW_TABLE = "furniture_overview";
overview is bad word to describe goal... 
Maybe something like `ProductViewStats` or `ProductViewMetrics`, or `ProductViewAnalytics`, or `ProductViewTracking`, or `ProductInteractionTracker`, and so on....

Actually in future this table may consist any metrics-related info for products?

2023-05-19 22:03 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/repository/FurnitureOverviewRepository.java
> +@Repository
@Repository is redundant

2023-05-19 22:07 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/repository/FurnitureUnitRepository.java
> +            "on fu.furniture_unit_id=fv.furniture_unit_id order by fv.view_per_day desc limit 10",
actually, in future 10 may be changed with any other number, e.g. 100 or 1000 because of constant expanding store.
Could you please to think of ability to use `properties` here?

2023-05-19 22:11 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/local/V229__insert_data_furniture_overview.sql
> +       (1000, 1000, 0, 100),
Please insert data in another way, in our database may be more furniture_unit_ids, so it may cause inconsistency. 

use insert with select query for it.

2023-05-22 12:42 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +    private final FurnitureOverviewRepository furnitureOverviewRepository;
Yes, I tested it

2023-05-22 12:42 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/TopFurnitureUnitJob.java
> +    private final FurnitureUnitService furnitureUnitService;
Yes, I tested it

2023-05-22 12:44 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/service/FurnitureUnitService.java
> +@EnableCaching
No it should be or in main class, or in services classes

2023-05-22 12:45 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +    private final FurnitureOverviewRepository furnitureOverviewRepository;
But here is no logic. What you mean?

2023-05-23 12:37 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/configuration/RedisConfig.java
> +    public RedisTemplate<String, Serializable> redisCacheTemplate(LettuceConnectionFactory redisConnectionFactory) {
<String, Serializable?>
Maybe just Object?

2023-05-23 12:38 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/FurnitureCountViewJob.java
> +    private final FurnitureOverviewRepository furnitureOverviewRepository;
youre using repository (DAO Layer) directly

2023-05-23 12:40 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/TopFurnitureUnitJob.java
> +    @Value("${webstore.furniture-unit.count-top-records:10}")
do not use default value in @Value

2023-05-23 12:41 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/TopFurnitureUnitJob.java
> +        furnitureUnitService.getTopFurnitureUnits(countTopRecords);
for what this job? result is ignored?

2023-05-23 12:46 UTC, sokimaaa commented on displayhandler/src/main/resources/application-dev.properties
> +webstore.furniture-unit.count-top-records=5
I think we may leave this propery in application.properties only

2023-05-23 12:50 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_product_view_tracking.sql
> +    furniture_unit_id bigserial not null,
bigserial is redundant for fk

2023-05-23 12:56 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V099__create_triggers.sql
> +for each row
did you test it? and move trigger to table-creating-script where related to

2023-05-23 12:57 UTC, sokimaaa commented on common/src/main/java/com/sokima/webstore/common/mapper/ObjectMapperConfiguration.java
> +        return new XmlMapper();
remove xml mapper if not needed

2023-05-23 12:58 UTC, sokimaaa commented on common/src/main/java/com/sokima/webstore/common/mapper/ObjectMapperConfiguration.java
> +    @Primary
and add Qualifier to fields where it used

2023-05-23 13:32 UTC, alexMIRON1 commented on displayhandler/src/main/java/com/sokima/webstore/display/configuration/RedisConfig.java
> +    public RedisTemplate<String, Serializable> redisCacheTemplate(LettuceConnectionFactory redisConnectionFactory) {
Redis requires data to be serialized when stored and deserialized when retrieved. When using "Serializable", objects serialized and deserialized automatically

2023-05-23 13:41 UTC, alexMIRON1 commented on displayhandler/src/main/resources/db/migration/base/V099__create_triggers.sql
> +for each row
Yes i did

2023-05-23 15:08 UTC, sokimaaa commented on displayhandler/src/main/java/com/sokima/webstore/display/logic/job/TopFurnitureUnitJob.java
> +        furnitureUnitService.getTopFurnitureUnits(countTopRecords);
1. why futniture service doing job about caching 
2. bad name for method

2023-05-23 15:13 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_product_view_tracking.sql
> +    furniture_unit_id int8 not null,
unique

2023-05-23 15:13 UTC, sokimaaa commented on displayhandler/src/main/resources/db/migration/base/V029__create_table_product_view_tracking.sql
> +    view_per_day bigint,
not null for views

2023-05-23 15:14 UTC, sokimaaa commented on displayhandler/src/test/java/com/sokima/webstore/display/logic/service/FurnitureUnitServiceTest.java
> +        ObjectMapper objectMapper = new ObjectMapper();
you created bean ObjectMapper and still using `new`

2023-05-29 14:51 UTC, sokimaaa approved these changes

2023-05-29 14:51 UTC, sokimaaa approved these changes

2023-05-29 14:52 UTC, merged